server:
  port: 9090

spring:
  datasource:
    url: jdbc:mysql://mj-spring-db.cvz74gn50fr7.us-west-2.rds.amazonaws.com:3306/study?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: admin
    password: escape123!
  jpa:
    show-sql: false
  jackson:
    property-naming-strategy= SNAKE_CASE